name: Count lines of code

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install Node.js
        uses: actions/setup-node@v2.1.5

      - name: install cloc
        run: npm i -g cloc

      - name: count lines of code
        id: count
        run: make count
        
      - name: comment on commit
        uses: peter-evans/commit-comment@v1.3.2
        with:
          body: "```${{steps.count.output}}```"
